stages:
  - test

test:7.0:
  stage: test
  image: bobey/docker-gitlab-ci-runner-php7
  cache:
    paths:
    - vendor/
  before_script:
    - composer update
  script:
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --coverage-text --colors=never --configuration ./build/phpunit.xml

test:5.6:
  stage: test
  image: bobey/docker-gitlab-ci-runner-php5.6
  cache:
    paths:
    - vendor/
  before_script:
    - composer update
  script:
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --coverage-text --colors=never --configuration ./build/phpunit.xml
