language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

notifications:
    email: true

before_script:
    - composer require phpunit/phpunit
    - composer update

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

